### ISSUE TITLE
relative path causes bash script to fail

### ISSUE THREAD

**Issue by arstgkneio** [arstgkneio/itsokayiguess#1]
in the monitor and display programs, after the directory was changed from an absolute to a relative path, the bash script which is executed from outside the directory is unable to launch the programs.
error code below:

```
pi@raspberrypi:~/Desktop $ Traceback (most recent call last):
  File "/home/pi/itsokayiguess/enPiromonitor/Display_Program.py", line 220, in <module>
    my_window['bg']=update_bg_color('0') # has same effect as the line above
  File "/home/pi/itsokayiguess/enPiromonitor/Display_Program.py", line 33, in update_bg_color
    raw_data_line = get_last_line().rstrip()
  File "/home/pi/itsokayiguess/enPiromonitor/Display_Program.py", line 19, in get_last_line
    datafile = file_list[-1] #most recent data file
IndexError: list index out of range
pi@raspberrypi:~/Desktop $ Traceback (most recent call last):
  File "/home/pi/itsokayiguess/enPiromonitor/Monitor_Program.py", line 83, in <module>
    save_log()
  File "/home/pi/itsokayiguess/enPiromonitor/Monitor_Program.py", line 53, in save_log
    with open(log_file, "a") as log:
FileNotFoundError: [Errno 2] No such file or directory: './environment_data/environment_data_20200418.csv'

```

**Comment by arstgkneio** [comment]
fixed in last commit using inspect.getfile to figure out path and os.path.realpath to set directory
