### ISSUE TITLE
monitor program still crashes when air quality sensor is not plugged in

### ISSUE THREAD

**Issue by arstgkneio** [arstgkneio/itsokayiguess#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/itsokayiguess/enPiromonitor/Monitor_Program.py", line 25, in <module>
    sensor = SDS011("/dev/ttyUSB0", use_query_mode=True)
  File "/home/pi/itsokayiguess/enPiromonitor/sds011.py", line 42, in __init__
    timeout=timeout)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```

possible solution: 

move 
`sensor = SDS011("/dev/ttyUSB0", use_query_mode=True)`

under 
`get_data(n=3):` definition

**Comment by arstgkneio** [comment]
fixed using try-except blocks
program now writes  and displays "n/a" for aqi/pmt columns in .csv file
