### ISSUE TITLE
display program fails to launch between noon and midnight

### ISSUE THREAD

**Issue by arstgkneio** [arstgkneio/itsokayiguess#3]
```
Traceback (most recent call last):
  File "/home/pi/itsokayiguess/enPiromonitor/Display_Program.py", line 372, in <module>
    update_time_last_measurement_data_label()
  File "/home/pi/itsokayiguess/enPiromonitor/Display_Program.py", line 254, in update_time_last_measurement_data_label
    dt_latest_obj = datetime.datetime.strptime(dt_latest, "%Y-%m-%d %I:%M:%S.%f")
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2020-04-19 14:44:20.642505' does not match format '%Y-%m-%d %I:%M:%S.%f'
```

**Comment by arstgkneio** [comment]
fixed by changing the format of time data
